// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proxy.proto

package proxy

import (
	context "context"
	"fmt"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

var (
	Proxy_DnsResolve_FullMethodName = "/proxy.Proxy/DnsResolve"
	Proxy_Proxy_FullMethodName      = "/proxy.Proxy/Proxy"
)

func SetServiceName(name string) {
	Proxy_ServiceDesc.ServiceName = name
	Proxy_DnsResolve_FullMethodName = fmt.Sprintf("/%s/DnsResolve", Proxy_ServiceDesc.ServiceName)
	Proxy_Proxy_FullMethodName = fmt.Sprintf("/%s/Proxy", Proxy_ServiceDesc.ServiceName)
}

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyClient interface {
	DnsResolve(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DnsRequest, DnsResponse], error)
	Proxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxySRC, ProxyDST], error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) DnsResolve(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DnsRequest, DnsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Proxy_ServiceDesc.Streams[0], Proxy_DnsResolve_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DnsRequest, DnsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Proxy_DnsResolveClient = grpc.BidiStreamingClient[DnsRequest, DnsResponse]

func (c *proxyClient) Proxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxySRC, ProxyDST], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Proxy_ServiceDesc.Streams[1], Proxy_Proxy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxySRC, ProxyDST]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Proxy_ProxyClient = grpc.BidiStreamingClient[ProxySRC, ProxyDST]

// ProxyServer is the server API for Proxy service.
// All implementations must embed UnimplementedProxyServer
// for forward compatibility.
type ProxyServer interface {
	DnsResolve(grpc.BidiStreamingServer[DnsRequest, DnsResponse]) error
	Proxy(grpc.BidiStreamingServer[ProxySRC, ProxyDST]) error
	mustEmbedUnimplementedProxyServer()
}

// UnimplementedProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServer struct{}

func (UnimplementedProxyServer) DnsResolve(grpc.BidiStreamingServer[DnsRequest, DnsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DnsResolve not implemented")
}
func (UnimplementedProxyServer) Proxy(grpc.BidiStreamingServer[ProxySRC, ProxyDST]) error {
	return status.Errorf(codes.Unimplemented, "method Proxy not implemented")
}
func (UnimplementedProxyServer) mustEmbedUnimplementedProxyServer() {}
func (UnimplementedProxyServer) testEmbeddedByValue()               {}

// UnsafeProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServer will
// result in compilation errors.
type UnsafeProxyServer interface {
	mustEmbedUnimplementedProxyServer()
}

func RegisterProxyServer(s grpc.ServiceRegistrar, srv ProxyServer) {
	// If the following call pancis, it indicates UnimplementedProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Proxy_ServiceDesc, srv)
}

func _Proxy_DnsResolve_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).DnsResolve(&grpc.GenericServerStream[DnsRequest, DnsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Proxy_DnsResolveServer = grpc.BidiStreamingServer[DnsRequest, DnsResponse]

func _Proxy_Proxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).Proxy(&grpc.GenericServerStream[ProxySRC, ProxyDST]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Proxy_ProxyServer = grpc.BidiStreamingServer[ProxySRC, ProxyDST]

// Proxy_ServiceDesc is the grpc.ServiceDesc for Proxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DnsResolve",
			Handler:       _Proxy_DnsResolve_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Proxy",
			Handler:       _Proxy_Proxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proxy.proto",
}
